server:
  port: 8072
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: false
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
          - Path=/organization/**
          filters:
          - RewritePath=/organization/(?<path>.*), /$\{path}
