spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    testWileIdle: true
    validationQuery: SELECT 1
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
eureka:
  instance:
  preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
keycloak:
  realm: spmia-realm
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: ZCdEJbAKJ8ErTcRc9oWkJ8B92MQdRalO
  use-resource-role-mapping: true
  bearer-only: true
